// <auto-generated />
using System;
using EtherpunkInventoryManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EtherpunkInventoryManagement.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20190211021836_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("EtherpunkInventoryManagement.Data.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Name");

                    b.Property<string>("NormalizedName");

                    b.HasKey("Id");

                    b.ToTable("ApplicationRoles");
                });

            modelBuilder.Entity("EtherpunkInventoryManagement.Data.HardwareAttachment", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("AttachmentData");

                    b.Property<string>("AttachmentFileName");

                    b.Property<string>("AttachmentName");

                    b.Property<string>("AttachmentTypeId");

                    b.Property<string>("CreatedByUserId");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("HardwareInventoryId");

                    b.Property<bool>("IsDeleted");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentTypeId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("HardwareInventoryId");

                    b.ToTable("HardwareAttachments");

                    b.HasData(
                        new
                        {
                            Id = "62796146-70e7-4fb9-9760-cd85a73df182",
                            AttachmentFileName = "invoice.pdf",
                            AttachmentName = "XPS 150 Invoice",
                            AttachmentTypeId = "e3e6af98-265b-4ebc-a290-60d65d50dd00",
                            CreatedByUserId = "9fa7c39d-a4c7-4c7c-9986-b48644c309af",
                            CreatedOn = new DateTime(2018, 8, 10, 20, 18, 36, 324, DateTimeKind.Local).AddTicks(8283),
                            HardwareInventoryId = "9a378792-3a2f-4682-ac17-17c798b9681d",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("EtherpunkInventoryManagement.Data.HardwareAttribute", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedByUserId");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("HardwareInventoryId");

                    b.Property<string>("HardwareLayoutTemplateId");

                    b.Property<string>("Notes");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("HardwareInventoryId");

                    b.HasIndex("HardwareLayoutTemplateId");

                    b.ToTable("HardwareAttributes");

                    b.HasData(
                        new
                        {
                            Id = "c45feaea-32ea-4d5b-85a0-abc639494260",
                            CreatedByUserId = "9fa7c39d-a4c7-4c7c-9986-b48644c309af",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 10, 10, 0, DateTimeKind.Unspecified),
                            HardwareInventoryId = "9a378792-3a2f-4682-ac17-17c798b9681d",
                            HardwareLayoutTemplateId = "f29cf67c-9a2c-47c8-9f72-eee55e6988d4",
                            Notes = ""
                        },
                        new
                        {
                            Id = "a17667c3-9906-49bb-98c2-c1a8309a97c6",
                            CreatedByUserId = "9fa7c39d-a4c7-4c7c-9986-b48644c309af",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 10, 10, 0, DateTimeKind.Unspecified),
                            HardwareInventoryId = "9a378792-3a2f-4682-ac17-17c798b9681d",
                            HardwareLayoutTemplateId = "7f30a163-7aec-47da-a87f-f6183a4745e3",
                            Notes = ""
                        },
                        new
                        {
                            Id = "6cd2b1c9-fafc-4dae-a42a-a45bca940184",
                            CreatedByUserId = "9fa7c39d-a4c7-4c7c-9986-b48644c309af",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 10, 10, 0, DateTimeKind.Unspecified),
                            HardwareInventoryId = "9a378792-3a2f-4682-ac17-17c798b9681d",
                            HardwareLayoutTemplateId = "b943d0eb-4807-46ab-9025-f0c73147468e",
                            Notes = ""
                        },
                        new
                        {
                            Id = "5959f2d2-3430-4d31-a59a-e36c0250bfc1",
                            CreatedByUserId = "9fa7c39d-a4c7-4c7c-9986-b48644c309af",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 10, 10, 0, DateTimeKind.Unspecified),
                            HardwareInventoryId = "9a378792-3a2f-4682-ac17-17c798b9681d",
                            HardwareLayoutTemplateId = "851c2fbd-39c8-4a75-b401-92d61a4347b4",
                            Notes = ""
                        },
                        new
                        {
                            Id = "f1672f5d-a885-494e-a5cb-3289a0d1f79a",
                            CreatedByUserId = "e194001e-6302-4b2b-9ccf-cb1ba8cc9ea4",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 11, 13, 0, DateTimeKind.Unspecified),
                            HardwareInventoryId = "9c8c0a85-4a31-4552-b8da-fd1114849829",
                            HardwareLayoutTemplateId = "f29cf67c-9a2c-47c8-9f72-eee55e6988d4",
                            Notes = ""
                        },
                        new
                        {
                            Id = "bc0f12ac-8785-4d81-97f0-71a24ab24d8e",
                            CreatedByUserId = "e194001e-6302-4b2b-9ccf-cb1ba8cc9ea4",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 11, 13, 0, DateTimeKind.Unspecified),
                            HardwareInventoryId = "9c8c0a85-4a31-4552-b8da-fd1114849829",
                            HardwareLayoutTemplateId = "7f30a163-7aec-47da-a87f-f6183a4745e3",
                            Notes = ""
                        },
                        new
                        {
                            Id = "3cdcc7f3-b148-4146-88fc-181047612eb5",
                            CreatedByUserId = "e194001e-6302-4b2b-9ccf-cb1ba8cc9ea4",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 11, 13, 0, DateTimeKind.Unspecified),
                            HardwareInventoryId = "9c8c0a85-4a31-4552-b8da-fd1114849829",
                            HardwareLayoutTemplateId = "b943d0eb-4807-46ab-9025-f0c73147468e",
                            Notes = ""
                        },
                        new
                        {
                            Id = "50d30d4d-c526-4a51-b405-b763dc5c2896",
                            CreatedByUserId = "e194001e-6302-4b2b-9ccf-cb1ba8cc9ea4",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 11, 13, 0, DateTimeKind.Unspecified),
                            HardwareInventoryId = "9c8c0a85-4a31-4552-b8da-fd1114849829",
                            HardwareLayoutTemplateId = "851c2fbd-39c8-4a75-b401-92d61a4347b4",
                            Notes = ""
                        },
                        new
                        {
                            Id = "cf0ffc9b-d879-4909-85ac-aeeebf4ef378",
                            CreatedByUserId = "d3ebdb0c-1884-4cde-ba8e-ade906609b99",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 13, 43, 0, DateTimeKind.Unspecified),
                            HardwareInventoryId = "30079d5e-83a4-4c12-9100-63b573c5dd6b",
                            HardwareLayoutTemplateId = "f29cf67c-9a2c-47c8-9f72-eee55e6988d4",
                            Notes = ""
                        },
                        new
                        {
                            Id = "8e336999-b0e5-4245-89c3-57e7e63c9fb2",
                            CreatedByUserId = "d3ebdb0c-1884-4cde-ba8e-ade906609b99",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 13, 43, 0, DateTimeKind.Unspecified),
                            HardwareInventoryId = "30079d5e-83a4-4c12-9100-63b573c5dd6b",
                            HardwareLayoutTemplateId = "7f30a163-7aec-47da-a87f-f6183a4745e3",
                            Notes = ""
                        },
                        new
                        {
                            Id = "110d5b05-3d43-4be6-a655-1e7f652ba66d",
                            CreatedByUserId = "d3ebdb0c-1884-4cde-ba8e-ade906609b99",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 13, 43, 0, DateTimeKind.Unspecified),
                            HardwareInventoryId = "30079d5e-83a4-4c12-9100-63b573c5dd6b",
                            HardwareLayoutTemplateId = "b943d0eb-4807-46ab-9025-f0c73147468e",
                            Notes = ""
                        },
                        new
                        {
                            Id = "479c9ba5-bacc-47e6-acb1-4488f01926aa",
                            CreatedByUserId = "d3ebdb0c-1884-4cde-ba8e-ade906609b99",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 13, 43, 0, DateTimeKind.Unspecified),
                            HardwareInventoryId = "30079d5e-83a4-4c12-9100-63b573c5dd6b",
                            HardwareLayoutTemplateId = "851c2fbd-39c8-4a75-b401-92d61a4347b4",
                            Notes = ""
                        },
                        new
                        {
                            Id = "67ae432b-3390-4acf-b724-83ec60d3b834",
                            CreatedByUserId = "f93b6937-dc27-4f8a-9d9b-5cc23c7d449d",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 15, 22, 0, DateTimeKind.Unspecified),
                            HardwareInventoryId = "68889378-4756-46a4-90c3-0ca178109a24",
                            HardwareLayoutTemplateId = "f29cf67c-9a2c-47c8-9f72-eee55e6988d4",
                            Notes = ""
                        },
                        new
                        {
                            Id = "cf1df671-224a-4e05-9558-99138988e988",
                            CreatedByUserId = "f93b6937-dc27-4f8a-9d9b-5cc23c7d449d",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 15, 22, 0, DateTimeKind.Unspecified),
                            HardwareInventoryId = "68889378-4756-46a4-90c3-0ca178109a24",
                            HardwareLayoutTemplateId = "7f30a163-7aec-47da-a87f-f6183a4745e3",
                            Notes = ""
                        },
                        new
                        {
                            Id = "6fca1bc2-cac4-403a-802a-15d5447682ee",
                            CreatedByUserId = "f93b6937-dc27-4f8a-9d9b-5cc23c7d449d",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 15, 22, 0, DateTimeKind.Unspecified),
                            HardwareInventoryId = "68889378-4756-46a4-90c3-0ca178109a24",
                            HardwareLayoutTemplateId = "b943d0eb-4807-46ab-9025-f0c73147468e",
                            Notes = ""
                        },
                        new
                        {
                            Id = "ca187d2b-2b4e-4027-9b21-f9ad6849cad4",
                            CreatedByUserId = "f93b6937-dc27-4f8a-9d9b-5cc23c7d449d",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 15, 22, 0, DateTimeKind.Unspecified),
                            HardwareInventoryId = "68889378-4756-46a4-90c3-0ca178109a24",
                            HardwareLayoutTemplateId = "851c2fbd-39c8-4a75-b401-92d61a4347b4",
                            Notes = ""
                        });
                });

            modelBuilder.Entity("EtherpunkInventoryManagement.Data.HardwareAudit", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("ActualCompletionDate")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AssignedUserId");

                    b.Property<string>("AuditPersonRoleLookupId");

                    b.Property<string>("CompletedByUserId");

                    b.Property<string>("CreatedByUserId");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ExpectedCompletionDate")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("HardwareInventoryId");

                    b.Property<string>("Notes");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("AuditPersonRoleLookupId");

                    b.HasIndex("CompletedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("HardwareInventoryId");

                    b.ToTable("HardwareAudits");

                    b.HasData(
                        new
                        {
                            Id = "8b9c9347-3189-43c8-9b7f-14d64dd19590",
                            ActualCompletionDate = new DateTime(2018, 10, 13, 20, 18, 36, 328, DateTimeKind.Local).AddTicks(6636),
                            AssignedUserId = "9fa7c39d-a4c7-4c7c-9986-b48644c309af",
                            AuditPersonRoleLookupId = "315929ad-1aaa-49f7-8499-e0f6e53b58d9",
                            CompletedByUserId = "9fa7c39d-a4c7-4c7c-9986-b48644c309af",
                            CreatedByUserId = "9fa7c39d-a4c7-4c7c-9986-b48644c309af",
                            CreatedOn = new DateTime(2018, 10, 10, 20, 18, 36, 328, DateTimeKind.Local).AddTicks(5544),
                            ExpectedCompletionDate = new DateTime(2018, 11, 10, 20, 18, 36, 328, DateTimeKind.Local).AddTicks(7268),
                            HardwareInventoryId = "9a378792-3a2f-4682-ac17-17c798b9681d",
                            Notes = "Fan making funny noise"
                        },
                        new
                        {
                            Id = "c4c9cbca-49a5-4083-8b55-02fbed2edff2",
                            ActualCompletionDate = new DateTime(2018, 10, 13, 20, 18, 36, 328, DateTimeKind.Local).AddTicks(8393),
                            AssignedUserId = "e194001e-6302-4b2b-9ccf-cb1ba8cc9ea4",
                            AuditPersonRoleLookupId = "fa9f1d43-87bb-4406-a3ca-280ea0e21909",
                            CompletedByUserId = "e194001e-6302-4b2b-9ccf-cb1ba8cc9ea4",
                            CreatedOn = new DateTime(2018, 10, 10, 20, 18, 36, 328, DateTimeKind.Local).AddTicks(8377),
                            ExpectedCompletionDate = new DateTime(2018, 11, 10, 20, 18, 36, 328, DateTimeKind.Local).AddTicks(8397),
                            HardwareInventoryId = "9c8c0a85-4a31-4552-b8da-fd1114849829",
                            Notes = ""
                        },
                        new
                        {
                            Id = "e3dda6f9-537e-4ce5-b71d-4847b55293fe",
                            AssignedUserId = "d3ebdb0c-1884-4cde-ba8e-ade906609b99",
                            AuditPersonRoleLookupId = "315929ad-1aaa-49f7-8499-e0f6e53b58d9",
                            CreatedOn = new DateTime(2018, 12, 10, 20, 18, 36, 328, DateTimeKind.Local).AddTicks(8422),
                            ExpectedCompletionDate = new DateTime(2019, 1, 10, 20, 18, 36, 328, DateTimeKind.Local).AddTicks(8426),
                            HardwareInventoryId = "30079d5e-83a4-4c12-9100-63b573c5dd6b",
                            Notes = ""
                        },
                        new
                        {
                            Id = "993cd2f2-d503-4d2c-85ae-85d7a9a8c464",
                            ActualCompletionDate = new DateTime(2018, 2, 13, 20, 18, 36, 328, DateTimeKind.Local).AddTicks(8434),
                            AssignedUserId = "d3ebdb0c-1884-4cde-ba8e-ade906609b99",
                            AuditPersonRoleLookupId = "315929ad-1aaa-49f7-8499-e0f6e53b58d9",
                            CompletedByUserId = "d3ebdb0c-1884-4cde-ba8e-ade906609b99",
                            CreatedOn = new DateTime(2018, 2, 10, 20, 18, 36, 328, DateTimeKind.Local).AddTicks(8434),
                            ExpectedCompletionDate = new DateTime(2018, 3, 10, 20, 18, 36, 328, DateTimeKind.Local).AddTicks(8438),
                            HardwareInventoryId = "30079d5e-83a4-4c12-9100-63b573c5dd6b",
                            Notes = ""
                        },
                        new
                        {
                            Id = "dda5fd7e-0e7f-418f-9a06-f5bf6a92634b",
                            ActualCompletionDate = new DateTime(2018, 2, 14, 20, 18, 36, 328, DateTimeKind.Local).AddTicks(8451),
                            AssignedUserId = "f93b6937-dc27-4f8a-9d9b-5cc23c7d449d",
                            AuditPersonRoleLookupId = "ba42df51-8a45-42d1-abbf-f4697596d4ac",
                            CompletedByUserId = "f93b6937-dc27-4f8a-9d9b-5cc23c7d449d",
                            CreatedOn = new DateTime(2018, 2, 10, 20, 18, 36, 328, DateTimeKind.Local).AddTicks(8447),
                            ExpectedCompletionDate = new DateTime(2018, 3, 10, 20, 18, 36, 328, DateTimeKind.Local).AddTicks(8455),
                            HardwareInventoryId = "68889378-4756-46a4-90c3-0ca178109a24",
                            Notes = ""
                        });
                });

            modelBuilder.Entity("EtherpunkInventoryManagement.Data.HardwareInventory", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AssignedUserId");

                    b.Property<string>("CreatedByUserId");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DatePurchased");

                    b.Property<string>("DisposedLookupId");

                    b.Property<DateTime?>("FutureReplacementDate");

                    b.Property<string>("HardwareLayoutId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ItemConditionId");

                    b.Property<string>("ItemConditionLookupId");

                    b.Property<string>("LocationDetails");

                    b.Property<string>("LocationId");

                    b.Property<string>("Name");

                    b.Property<string>("Notes");

                    b.Property<string>("ShortId");

                    b.Property<string>("VendorId");

                    b.Property<DateTime?>("WarrantyExpiration");

                    b.Property<string>("WarrantyNotes");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DisposedLookupId");

                    b.HasIndex("HardwareLayoutId");

                    b.HasIndex("ItemConditionId");

                    b.HasIndex("LocationId");

                    b.HasIndex("VendorId");

                    b.ToTable("HardwareInventories");

                    b.HasData(
                        new
                        {
                            Id = "9a378792-3a2f-4682-ac17-17c798b9681d",
                            AssignedUserId = "9fa7c39d-a4c7-4c7c-9986-b48644c309af",
                            CreatedByUserId = "9fa7c39d-a4c7-4c7c-9986-b48644c309af",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 10, 10, 0, DateTimeKind.Unspecified),
                            DatePurchased = new DateTime(2016, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FutureReplacementDate = new DateTime(2019, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HardwareLayoutId = "c7cfb168-e8b9-4b31-a5b8-504fb77cd449",
                            IsDeleted = false,
                            ItemConditionLookupId = "3487407e-ea58-47b4-ba2a-e3642ccfd4f4",
                            LocationDetails = "On Kennys desk",
                            LocationId = "721ee439-8040-4b3e-b047-6b44b1057e73",
                            Name = "Developer machine",
                            Notes = "",
                            ShortId = "EI-YFK-VV8-WDG",
                            VendorId = "0541cd81-b043-4b65-900c-812dcad5692e",
                            WarrantyExpiration = new DateTime(2018, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WarrantyNotes = "Call 1-888-541-9284 for tech support; Call 1-877-483-1139 for warranty stuff"
                        },
                        new
                        {
                            Id = "9c8c0a85-4a31-4552-b8da-fd1114849829",
                            AssignedUserId = "e194001e-6302-4b2b-9ccf-cb1ba8cc9ea4",
                            CreatedByUserId = "9fa7c39d-a4c7-4c7c-9986-b48644c309af",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 11, 13, 0, DateTimeKind.Unspecified),
                            DatePurchased = new DateTime(2016, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HardwareLayoutId = "c7cfb168-e8b9-4b31-a5b8-504fb77cd449",
                            IsDeleted = false,
                            ItemConditionLookupId = "3487407e-ea58-47b4-ba2a-e3642ccfd4f4",
                            LocationDetails = "On Doug's desk",
                            LocationId = "721ee439-8040-4b3e-b047-6b44b1057e73",
                            Name = "",
                            Notes = "",
                            ShortId = "EI-QQF-DKH-KY8",
                            VendorId = "0541cd81-b043-4b65-900c-812dcad5692e",
                            WarrantyExpiration = new DateTime(2018, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WarrantyNotes = "Call 1-877-555-1111, Extension 5, Previous tech code 815A3"
                        },
                        new
                        {
                            Id = "30079d5e-83a4-4c12-9100-63b573c5dd6b",
                            AssignedUserId = "d3ebdb0c-1884-4cde-ba8e-ade906609b99",
                            CreatedByUserId = "9fa7c39d-a4c7-4c7c-9986-b48644c309af",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 13, 43, 0, DateTimeKind.Unspecified),
                            DatePurchased = new DateTime(2016, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HardwareLayoutId = "c7cfb168-e8b9-4b31-a5b8-504fb77cd449",
                            IsDeleted = false,
                            ItemConditionLookupId = "16719bae-4ed1-492e-8d85-0ce7332e088d",
                            LocationDetails = "",
                            LocationId = "721ee439-8040-4b3e-b047-6b44b1057e73",
                            Name = "",
                            Notes = "",
                            ShortId = "EI-M34-47F-BTX",
                            VendorId = "0541cd81-b043-4b65-900c-812dcad5692e",
                            WarrantyExpiration = new DateTime(2018, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            WarrantyNotes = "Call 1-877-555-1111, Extension 5, Previous tech code 815A3"
                        },
                        new
                        {
                            Id = "68889378-4756-46a4-90c3-0ca178109a24",
                            AssignedUserId = "f93b6937-dc27-4f8a-9d9b-5cc23c7d449d",
                            CreatedByUserId = "9fa7c39d-a4c7-4c7c-9986-b48644c309af",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 15, 22, 0, DateTimeKind.Unspecified),
                            DatePurchased = new DateTime(2016, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HardwareLayoutId = "c7cfb168-e8b9-4b31-a5b8-504fb77cd449",
                            IsDeleted = false,
                            ItemConditionLookupId = "3487407e-ea58-47b4-ba2a-e3642ccfd4f4",
                            LocationDetails = "",
                            LocationId = "721ee439-8040-4b3e-b047-6b44b1057e73",
                            Name = "",
                            Notes = "",
                            ShortId = "EI-46V-7F8-AQ3",
                            VendorId = "0541cd81-b043-4b65-900c-812dcad5692e",
                            WarrantyNotes = "Call 1-877-555-1111, Extension 5, Previous tech code 815A3"
                        });
                });

            modelBuilder.Entity("EtherpunkInventoryManagement.Data.HardwareInventoryAssignmentHistory", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AssignedBy_UserId");

                    b.Property<string>("AssignedTo_UserId");

                    b.Property<string>("CreatedByUserId");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("HardwareInventoryId");

                    b.Property<string>("Notes");

                    b.HasKey("Id");

                    b.HasIndex("AssignedBy_UserId");

                    b.HasIndex("AssignedTo_UserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("HardwareInventoryId");

                    b.ToTable("HardwareInventoryAssignmentHistories");

                    b.HasData(
                        new
                        {
                            Id = "201b1b65-5ccd-4360-92c5-aab3fdc88e5a",
                            AssignedBy_UserId = "9fa7c39d-a4c7-4c7c-9986-b48644c309af",
                            AssignedTo_UserId = "9fa7c39d-a4c7-4c7c-9986-b48644c309af",
                            CreatedByUserId = "9fa7c39d-a4c7-4c7c-9986-b48644c309af",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 10, 10, 0, DateTimeKind.Unspecified),
                            HardwareInventoryId = "9a378792-3a2f-4682-ac17-17c798b9681d",
                            Notes = "Initial designation."
                        },
                        new
                        {
                            Id = "3e2c865f-90d3-4f0c-969d-f804c2b6c16a",
                            AssignedBy_UserId = "e194001e-6302-4b2b-9ccf-cb1ba8cc9ea4",
                            AssignedTo_UserId = "e194001e-6302-4b2b-9ccf-cb1ba8cc9ea4",
                            CreatedByUserId = "e194001e-6302-4b2b-9ccf-cb1ba8cc9ea4",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 11, 13, 0, DateTimeKind.Unspecified),
                            HardwareInventoryId = "9c8c0a85-4a31-4552-b8da-fd1114849829",
                            Notes = "Initial designation."
                        },
                        new
                        {
                            Id = "468e5c12-9d4d-40d1-b31d-71a92cd39736",
                            AssignedBy_UserId = "d3ebdb0c-1884-4cde-ba8e-ade906609b99",
                            AssignedTo_UserId = "d3ebdb0c-1884-4cde-ba8e-ade906609b99",
                            CreatedByUserId = "d3ebdb0c-1884-4cde-ba8e-ade906609b99",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 13, 43, 0, DateTimeKind.Unspecified),
                            HardwareInventoryId = "30079d5e-83a4-4c12-9100-63b573c5dd6b",
                            Notes = "Initial designation."
                        },
                        new
                        {
                            Id = "1a35c031-489b-4773-b08a-b270035d20d5",
                            AssignedBy_UserId = "f93b6937-dc27-4f8a-9d9b-5cc23c7d449d",
                            AssignedTo_UserId = "f93b6937-dc27-4f8a-9d9b-5cc23c7d449d",
                            CreatedByUserId = "f93b6937-dc27-4f8a-9d9b-5cc23c7d449d",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 15, 22, 0, DateTimeKind.Unspecified),
                            HardwareInventoryId = "68889378-4756-46a4-90c3-0ca178109a24",
                            Notes = "Initial designation."
                        });
                });

            modelBuilder.Entity("EtherpunkInventoryManagement.Data.HardwareLayout", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedByUserId");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDelete");

                    b.Property<string>("Name");

                    b.Property<string>("Notes");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("HardwareLayouts");

                    b.HasData(
                        new
                        {
                            Id = "c7cfb168-e8b9-4b31-a5b8-504fb77cd449",
                            CreatedByUserId = "9fa7c39d-a4c7-4c7c-9986-b48644c309af",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 8, 43, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            Name = "Dell XPS 150",
                            Notes = ""
                        });
                });

            modelBuilder.Entity("EtherpunkInventoryManagement.Data.HardwareLayoutTemplate", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedByUserId");

                    b.Property<string>("Datatype_LookupId");

                    b.Property<string>("HardwareLayoutId");

                    b.Property<string>("HardwareLayoutTemplate_LookupId");

                    b.Property<string>("HardwareLayoutTemplate_TypeLookupId");

                    b.Property<int>("OrderIndex");

                    b.Property<string>("PropertyValue");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Datatype_LookupId");

                    b.HasIndex("HardwareLayoutId");

                    b.HasIndex("HardwareLayoutTemplate_LookupId");

                    b.ToTable("HardwareLayoutTemplates");

                    b.HasData(
                        new
                        {
                            Id = "f29cf67c-9a2c-47c8-9f72-eee55e6988d4",
                            CreatedByUserId = "9fa7c39d-a4c7-4c7c-9986-b48644c309af",
                            Datatype_LookupId = "2495bce9-8632-4681-9a10-5ea00f9eeb37",
                            HardwareLayoutId = "c7cfb168-e8b9-4b31-a5b8-504fb77cd449",
                            HardwareLayoutTemplate_TypeLookupId = "2e7d8395-6638-4fad-9103-09d05c901354",
                            OrderIndex = 1,
                            PropertyValue = "Dell"
                        },
                        new
                        {
                            Id = "b943d0eb-4807-46ab-9025-f0c73147468e",
                            CreatedByUserId = "9fa7c39d-a4c7-4c7c-9986-b48644c309af",
                            Datatype_LookupId = "7453eab1-8609-42cd-9460-b469c83c1e6a",
                            HardwareLayoutId = "c7cfb168-e8b9-4b31-a5b8-504fb77cd449",
                            HardwareLayoutTemplate_TypeLookupId = "0f7feb72-c67b-4ad1-a536-328a36c0a864",
                            OrderIndex = 4,
                            PropertyValue = "8"
                        },
                        new
                        {
                            Id = "7f30a163-7aec-47da-a87f-f6183a4745e3",
                            CreatedByUserId = "9fa7c39d-a4c7-4c7c-9986-b48644c309af",
                            Datatype_LookupId = "2495bce9-8632-4681-9a10-5ea00f9eeb37",
                            HardwareLayoutId = "c7cfb168-e8b9-4b31-a5b8-504fb77cd449",
                            HardwareLayoutTemplate_TypeLookupId = "2e7d8395-6638-4fad-9103-09d05c901354",
                            OrderIndex = 2,
                            PropertyValue = "XPS 150"
                        },
                        new
                        {
                            Id = "851c2fbd-39c8-4a75-b401-92d61a4347b4",
                            CreatedByUserId = "9fa7c39d-a4c7-4c7c-9986-b48644c309af",
                            Datatype_LookupId = "5f8ab34b-e60d-4e5a-bd5c-83f4b268812a",
                            HardwareLayoutId = "c7cfb168-e8b9-4b31-a5b8-504fb77cd449",
                            HardwareLayoutTemplate_TypeLookupId = "db3b0c57-2231-4b8f-9d95-1c7f6ee21cf8",
                            OrderIndex = 3,
                            PropertyValue = "678.93"
                        });
                });

            modelBuilder.Entity("EtherpunkInventoryManagement.Data.Location", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abbreviation");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("CreatedByUserId");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FaxNumber");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LocationName");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("State");

                    b.Property<string>("Street1");

                    b.Property<string>("Street2");

                    b.Property<string>("Zip");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = "721ee439-8040-4b3e-b047-6b44b1057e73",
                            Abbreviation = "BMT",
                            City = "Beaumont",
                            Country = "US",
                            CreatedByUserId = "9fa7c39d-a4c7-4c7c-9986-b48644c309af",
                            CreatedOn = new DateTime(2017, 1, 22, 11, 0, 13, 0, DateTimeKind.Unspecified),
                            FaxNumber = "1-888-111-1111",
                            IsDeleted = false,
                            LocationName = "Beamont Office",
                            PhoneNumber = "409-444-1111",
                            State = "TX",
                            Street1 = "103 Bird Street",
                            Street2 = "",
                            Zip = "77701"
                        });
                });

            modelBuilder.Entity("EtherpunkInventoryManagement.Data.Lookup", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LookupName");

                    b.Property<string>("LookupType");

                    b.HasKey("Id");

                    b.ToTable("Lookups");

                    b.HasData(
                        new
                        {
                            Id = "fa9f1d43-87bb-4406-a3ca-280ea0e21909",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(6793),
                            LookupName = "Supervisor",
                            LookupType = "AuditPersonRole"
                        },
                        new
                        {
                            Id = "315929ad-1aaa-49f7-8499-e0f6e53b58d9",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(8961),
                            LookupName = "Tech",
                            LookupType = "AuditPersonRole"
                        },
                        new
                        {
                            Id = "ba42df51-8a45-42d1-abbf-f4697596d4ac",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(8994),
                            LookupName = "Supervisor",
                            LookupType = "AuditPersonRole"
                        },
                        new
                        {
                            Id = "e3e6af98-265b-4ebc-a290-60d65d50dd00",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(8998),
                            LookupName = "Invoice",
                            LookupType = "BinaryDatatype"
                        },
                        new
                        {
                            Id = "89fbc095-3965-4818-a221-4863c33699d9",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9002),
                            LookupName = "License",
                            LookupType = "BinaryDatatype"
                        },
                        new
                        {
                            Id = "18207c02-ca41-402d-95bb-a09d107a1795",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9014),
                            LookupName = "Picture",
                            LookupType = "BinaryDatatype"
                        },
                        new
                        {
                            Id = "d9c5c265-a220-4ca3-abbe-65b71d104704",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9010),
                            LookupName = "Other",
                            LookupType = "BinaryDatatype"
                        },
                        new
                        {
                            Id = "5f4aaee8-c55c-4d13-9ba2-f4a10ba66da1",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9031),
                            LookupName = "Capacity MB",
                            LookupType = "Datatype"
                        },
                        new
                        {
                            Id = "7453eab1-8609-42cd-9460-b469c83c1e6a",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9026),
                            LookupName = "Capacity GB",
                            LookupType = "Datatype"
                        },
                        new
                        {
                            Id = "b4be67cd-6e01-4caa-be04-c01971a27988",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9035),
                            LookupName = "Capacity TB",
                            LookupType = "Datatype"
                        },
                        new
                        {
                            Id = "5f8ab34b-e60d-4e5a-bd5c-83f4b268812a",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9039),
                            LookupName = "Currency",
                            LookupType = "Datatype"
                        },
                        new
                        {
                            Id = "7c145e98-5528-47e6-b385-e56cb906f69e",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9043),
                            LookupName = "Integer",
                            LookupType = "Datatype"
                        },
                        new
                        {
                            Id = "b1c86a47-1e49-4f83-935a-5e9ac39059a0",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9047),
                            LookupName = "Real",
                            LookupType = "Datatype"
                        },
                        new
                        {
                            Id = "2495bce9-8632-4681-9a10-5ea00f9eeb37",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9051),
                            LookupName = "String",
                            LookupType = "Datatype"
                        },
                        new
                        {
                            Id = "d03b0c23-e14e-4afb-b565-adbe0f3da51c",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9055),
                            LookupName = "Destroyed",
                            LookupType = "DisposalMethod"
                        },
                        new
                        {
                            Id = "987ffdc8-f90d-46bf-a0ac-4b09784852b7",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9059),
                            LookupName = "Donated",
                            LookupType = "DisposalMethod"
                        },
                        new
                        {
                            Id = "db3475df-4cde-41ad-ab1e-6081d4e7a105",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9063),
                            LookupName = "Sold",
                            LookupType = "DisposalMethod"
                        },
                        new
                        {
                            Id = "659aec90-c918-49b5-b626-85a58a4255c4",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9170),
                            LookupName = "New",
                            LookupType = "ItemCondition"
                        },
                        new
                        {
                            Id = "3487407e-ea58-47b4-ba2a-e3642ccfd4f4",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9166),
                            LookupName = "Good",
                            LookupType = "ItemCondition"
                        },
                        new
                        {
                            Id = "16719bae-4ed1-492e-8d85-0ce7332e088d",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9174),
                            LookupName = "Poor",
                            LookupType = "ItemCondition"
                        },
                        new
                        {
                            Id = "05cececd-9719-4a9a-bf51-2e15f31faa5b",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9178),
                            LookupName = "Possibly Broken",
                            LookupType = "ItemCondition"
                        },
                        new
                        {
                            Id = "01153d43-6f74-49e2-a191-88ed5237df96",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9162),
                            LookupName = "Broke",
                            LookupType = "ItemCondition"
                        },
                        new
                        {
                            Id = "d07801e2-981b-4163-9dd6-79483ae63628",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9182),
                            LookupName = "Unknown",
                            LookupType = "ItemCondition"
                        },
                        new
                        {
                            Id = "107ca0c2-fe5c-49e5-909c-4fb0d4f6e915",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9067),
                            LookupName = "Graphics Card",
                            LookupType = "HardwareTemplateLayout"
                        },
                        new
                        {
                            Id = "2e7d8395-6638-4fad-9103-09d05c901354",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9072),
                            LookupName = "Make",
                            LookupType = "HardwareTemplateLayout"
                        },
                        new
                        {
                            Id = "0f7feb72-c67b-4ad1-a536-328a36c0a864",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9076),
                            LookupName = "Memory",
                            LookupType = "HardwareTemplateLayout"
                        },
                        new
                        {
                            Id = "212f7b7e-df8f-424b-8ca4-a4ace16ae831",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9080),
                            LookupName = "Model",
                            LookupType = "HardwareTemplateLayout"
                        },
                        new
                        {
                            Id = "db3b0c57-2231-4b8f-9d95-1c7f6ee21cf8",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9141),
                            LookupName = "Price",
                            LookupType = "HardwareTemplateLayout"
                        },
                        new
                        {
                            Id = "ac3d39cb-ca09-4716-a57c-210c26828d16",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9150),
                            LookupName = "Processor",
                            LookupType = "HardwareTemplateLayout"
                        },
                        new
                        {
                            Id = "fc77a71a-77f5-4a01-80e8-fb54d47a883f",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9154),
                            LookupName = "Serial Number",
                            LookupType = "HardwareTemplateLayout"
                        },
                        new
                        {
                            Id = "9147c301-271c-4faf-bb36-cd44cf54b5dc",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9158),
                            LookupName = "Storage Capacity",
                            LookupType = "HardwareTemplateLayout"
                        },
                        new
                        {
                            Id = "ef13987e-7276-4961-9008-bbed538382d5",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9187),
                            LookupName = "Hardware",
                            LookupType = "TemplateType"
                        },
                        new
                        {
                            Id = "02ec251c-d9d7-4438-9a01-c970dee721c4",
                            CreatedOn = new DateTime(2019, 2, 11, 2, 18, 36, 301, DateTimeKind.Utc).AddTicks(9191),
                            LookupName = "Software",
                            LookupType = "TemplateType"
                        });
                });

            modelBuilder.Entity("EtherpunkInventoryManagement.Data.Vendor", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("CreatedByUserId");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FaxNumber");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name");

                    b.Property<string>("Notes");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("State");

                    b.Property<string>("Street1");

                    b.Property<string>("Street2");

                    b.Property<string>("TechSupportNumber");

                    b.Property<string>("Zip");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Vendors");

                    b.HasData(
                        new
                        {
                            Id = "0541cd81-b043-4b65-900c-812dcad5692e",
                            City = "Dallas",
                            Country = "US",
                            CreatedByUserId = "9fa7c39d-a4c7-4c7c-9986-b48644c309af",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 5, 13, 0, DateTimeKind.Unspecified),
                            Email = "support@dell.com",
                            FaxNumber = "866-444-5454",
                            IsDeleted = false,
                            Name = "Dell",
                            Notes = "Extension 5310 then press 9",
                            PhoneNumber = "855-393-2299",
                            State = "TX",
                            Street1 = "521 West End Blvd",
                            Street2 = "",
                            TechSupportNumber = "800-630-2910",
                            Zip = "77618"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "6d68a30e-caec-45d4-9df7-126478e0fa04",
                            ConcurrencyStamp = "d470da95-ee2b-42b2-bbbf-5f0cf47633c9",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "d6b28bd3-fffe-4762-bc37-1a63c6d06780",
                            ConcurrencyStamp = "844ab6fd-00f4-4be5-85ed-99f1e2a3d140",
                            Name = "Superviser",
                            NormalizedName = "SUPERVISER"
                        },
                        new
                        {
                            Id = "0416334c-8efe-4fb5-ad4f-7fd69744c228",
                            ConcurrencyStamp = "2aecd0ff-70cd-4dd4-9326-4e17f8839f98",
                            Name = "Tech",
                            NormalizedName = "TECH"
                        },
                        new
                        {
                            Id = "6b30374c-4005-4021-8e4b-b64e53e68a80",
                            ConcurrencyStamp = "e8be4888-0461-4ae0-a567-7decdeb5f2fa",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUserRole<string>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("EtherpunkInventoryManagement.Data.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("ActiveDirectoryGuid");

                    b.Property<string>("ActiveDirectoryUserName");

                    b.Property<string>("CreatedByUserId");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsDisabled");

                    b.Property<string>("LastName");

                    b.HasIndex("CreatedByUserId");

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "4b64005b-9d67-42f6-aef0-048353afa97b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "05e9d5df-1cd4-47cc-972c-f4744c1cdfd1",
                            Email = "admin@admin.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN@ADMIN.COM",
                            PasswordHash = "ALRDW0BNNACzQlyOjWu2SsZxHq4xU7oNofmkXEE6T+R324Lp48SOgC/I4Agb1JgFZA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d1db9722-9352-4db2-806a-7933c13abfaa",
                            TwoFactorEnabled = false,
                            UserName = "admin@admin.com",
                            CreatedOn = new DateTime(2017, 1, 22, 11, 30, 6, 0, DateTimeKind.Unspecified),
                            FirstName = "Admin",
                            IsDeleted = false,
                            IsDisabled = true,
                            LastName = "Admin"
                        },
                        new
                        {
                            Id = "9fa7c39d-a4c7-4c7c-9986-b48644c309af",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7f2737a0-574e-4b53-854d-472c75d154f9",
                            Email = "kmann@etherpunk.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "KMANN@ETHERPUNK.COM",
                            NormalizedUserName = "KMANN@ETHERPUNK.COM",
                            PasswordHash = "AJsDjcaPLcFFqWAZv9sOYwC7LiauV0wV13gfH40NLDQ6OIbyPxYw8wsXEHXXl5dfVA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "18134513-41e9-4ee7-824a-327ffa04d4a3",
                            TwoFactorEnabled = false,
                            UserName = "kmann@etherpunk.com",
                            CreatedOn = new DateTime(2017, 1, 22, 11, 0, 13, 0, DateTimeKind.Unspecified),
                            FirstName = "Kenny",
                            IsDeleted = false,
                            IsDisabled = false,
                            LastName = "Mann"
                        },
                        new
                        {
                            Id = "e194001e-6302-4b2b-9ccf-cb1ba8cc9ea4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "537b73c4-163d-4094-a6d5-96652bd2d602",
                            Email = "dbrooks@etherpunk.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "DBROOKS@ETHERPUNK.COM",
                            NormalizedUserName = "DBROOKS@ETHERPUNK.COM",
                            PasswordHash = "AD92BPSbLwQc6chOIjqZCJGZpfQCw2lwCrpBcU3Oen6aKuntGTiXeC5kY/Kadxs16w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1a341a2c-9397-4e27-8a2b-be9952e196e8",
                            TwoFactorEnabled = false,
                            UserName = "dbrooks@etherpunk.com",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 0, 14, 0, DateTimeKind.Unspecified),
                            FirstName = "Doug",
                            IsDeleted = false,
                            IsDisabled = false,
                            LastName = "Brooks"
                        },
                        new
                        {
                            Id = "d3ebdb0c-1884-4cde-ba8e-ade906609b99",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c4d09148-fe3a-43bc-ad96-348dd494957f",
                            Email = "njean@etherpunk.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "NJEAN@ETHERPUNK.COM",
                            NormalizedUserName = "NJEAN@ETHERPUNK.COM",
                            PasswordHash = "APdVo9EYBJU5b93w/1wvYnd0Fdxh0Gi80qoa6g8WYpiDVkyozuEKEOvuibyH/JamnA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6c57daf5-5131-495c-8b67-6252a69a9e84",
                            TwoFactorEnabled = false,
                            UserName = "njean@etherpunk.com",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 0, 15, 0, DateTimeKind.Unspecified),
                            FirstName = "Norma",
                            IsDeleted = false,
                            IsDisabled = false,
                            LastName = "Jean"
                        },
                        new
                        {
                            Id = "f93b6937-dc27-4f8a-9d9b-5cc23c7d449d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e344f6b2-6ce6-4343-a53e-cc65511537cb",
                            Email = "ssmith@etherpunk.com",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "SSMITH@ETHERPUNK.COM",
                            NormalizedUserName = "SSMITH@ETHERPUNK.COM",
                            PasswordHash = "AEcAbg0OYVGWULi9sxi0iKqlnNWiS/S4ne7A9w5ZVRz/lNyNYVYnij86CDl+AwP7gQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7c8af355-a5d1-4900-8110-ed0abac45251",
                            TwoFactorEnabled = false,
                            UserName = "ssmith@etherpunk.com",
                            CreatedOn = new DateTime(2017, 1, 22, 12, 0, 16, 0, DateTimeKind.Unspecified),
                            FirstName = "Stephanie",
                            IsDeleted = false,
                            IsDisabled = false,
                            LastName = "Smith"
                        });
                });

            modelBuilder.Entity("EtherpunkInventoryManagement.Data.ApplicationUserRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserRole<string>");

                    b.Property<string>("ApplicationRoleId");

                    b.Property<string>("ApplicationUserId");

                    b.HasIndex("ApplicationRoleId");

                    b.HasIndex("ApplicationUserId");

                    b.HasDiscriminator().HasValue("ApplicationUserRole");

                    b.HasData(
                        new
                        {
                            UserId = "4b64005b-9d67-42f6-aef0-048353afa97b",
                            RoleId = "6d68a30e-caec-45d4-9df7-126478e0fa04"
                        },
                        new
                        {
                            UserId = "9fa7c39d-a4c7-4c7c-9986-b48644c309af",
                            RoleId = "0416334c-8efe-4fb5-ad4f-7fd69744c228"
                        },
                        new
                        {
                            UserId = "e194001e-6302-4b2b-9ccf-cb1ba8cc9ea4",
                            RoleId = "d6b28bd3-fffe-4762-bc37-1a63c6d06780"
                        },
                        new
                        {
                            UserId = "d3ebdb0c-1884-4cde-ba8e-ade906609b99",
                            RoleId = "0416334c-8efe-4fb5-ad4f-7fd69744c228"
                        },
                        new
                        {
                            UserId = "f93b6937-dc27-4f8a-9d9b-5cc23c7d449d",
                            RoleId = "6b30374c-4005-4021-8e4b-b64e53e68a80"
                        });
                });

            modelBuilder.Entity("EtherpunkInventoryManagement.Data.HardwareAttachment", b =>
                {
                    b.HasOne("EtherpunkInventoryManagement.Data.Lookup", "AttachmentType")
                        .WithMany()
                        .HasForeignKey("AttachmentTypeId");

                    b.HasOne("EtherpunkInventoryManagement.Data.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("EtherpunkInventoryManagement.Data.HardwareInventory", "HardwareInventory")
                        .WithMany("Attachments")
                        .HasForeignKey("HardwareInventoryId");
                });

            modelBuilder.Entity("EtherpunkInventoryManagement.Data.HardwareAttribute", b =>
                {
                    b.HasOne("EtherpunkInventoryManagement.Data.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("EtherpunkInventoryManagement.Data.HardwareInventory", "HardwareInventory")
                        .WithMany("HardwareAttributes")
                        .HasForeignKey("HardwareInventoryId");

                    b.HasOne("EtherpunkInventoryManagement.Data.HardwareLayoutTemplate", "HardwareLayoutTemplate")
                        .WithMany()
                        .HasForeignKey("HardwareLayoutTemplateId");
                });

            modelBuilder.Entity("EtherpunkInventoryManagement.Data.HardwareAudit", b =>
                {
                    b.HasOne("EtherpunkInventoryManagement.Data.ApplicationUser", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId");

                    b.HasOne("EtherpunkInventoryManagement.Data.Lookup", "AuditPersonRoleLookup")
                        .WithMany()
                        .HasForeignKey("AuditPersonRoleLookupId");

                    b.HasOne("EtherpunkInventoryManagement.Data.ApplicationUser", "CompletedByUser")
                        .WithMany()
                        .HasForeignKey("CompletedByUserId");

                    b.HasOne("EtherpunkInventoryManagement.Data.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("EtherpunkInventoryManagement.Data.HardwareInventory", "HardwareInventory")
                        .WithMany()
                        .HasForeignKey("HardwareInventoryId");
                });

            modelBuilder.Entity("EtherpunkInventoryManagement.Data.HardwareInventory", b =>
                {
                    b.HasOne("EtherpunkInventoryManagement.Data.ApplicationUser", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId");

                    b.HasOne("EtherpunkInventoryManagement.Data.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("EtherpunkInventoryManagement.Data.Lookup", "DisposedLookup")
                        .WithMany()
                        .HasForeignKey("DisposedLookupId");

                    b.HasOne("EtherpunkInventoryManagement.Data.HardwareLayout", "HardwareLayout")
                        .WithMany()
                        .HasForeignKey("HardwareLayoutId");

                    b.HasOne("EtherpunkInventoryManagement.Data.Lookup", "ItemCondition")
                        .WithMany()
                        .HasForeignKey("ItemConditionId");

                    b.HasOne("EtherpunkInventoryManagement.Data.Location")
                        .WithMany("HardwareInventories")
                        .HasForeignKey("LocationId");

                    b.HasOne("EtherpunkInventoryManagement.Data.Vendor", "Vendor")
                        .WithMany("HardwareInventories")
                        .HasForeignKey("VendorId");
                });

            modelBuilder.Entity("EtherpunkInventoryManagement.Data.HardwareInventoryAssignmentHistory", b =>
                {
                    b.HasOne("EtherpunkInventoryManagement.Data.ApplicationUser", "AssignedBy_User")
                        .WithMany()
                        .HasForeignKey("AssignedBy_UserId");

                    b.HasOne("EtherpunkInventoryManagement.Data.ApplicationUser", "AssignedTo_User")
                        .WithMany()
                        .HasForeignKey("AssignedTo_UserId");

                    b.HasOne("EtherpunkInventoryManagement.Data.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("EtherpunkInventoryManagement.Data.HardwareInventory", "HardwareInventory")
                        .WithMany()
                        .HasForeignKey("HardwareInventoryId");
                });

            modelBuilder.Entity("EtherpunkInventoryManagement.Data.HardwareLayout", b =>
                {
                    b.HasOne("EtherpunkInventoryManagement.Data.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");
                });

            modelBuilder.Entity("EtherpunkInventoryManagement.Data.HardwareLayoutTemplate", b =>
                {
                    b.HasOne("EtherpunkInventoryManagement.Data.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("EtherpunkInventoryManagement.Data.Lookup", "DataType_Lookup")
                        .WithMany()
                        .HasForeignKey("Datatype_LookupId");

                    b.HasOne("EtherpunkInventoryManagement.Data.HardwareLayout", "HardwareLayout")
                        .WithMany()
                        .HasForeignKey("HardwareLayoutId");

                    b.HasOne("EtherpunkInventoryManagement.Data.Lookup", "HardwareLayoutTemplate_Lookup")
                        .WithMany()
                        .HasForeignKey("HardwareLayoutTemplate_LookupId");
                });

            modelBuilder.Entity("EtherpunkInventoryManagement.Data.Location", b =>
                {
                    b.HasOne("EtherpunkInventoryManagement.Data.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");
                });

            modelBuilder.Entity("EtherpunkInventoryManagement.Data.Vendor", b =>
                {
                    b.HasOne("EtherpunkInventoryManagement.Data.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EtherpunkInventoryManagement.Data.ApplicationUser", b =>
                {
                    b.HasOne("EtherpunkInventoryManagement.Data.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");
                });

            modelBuilder.Entity("EtherpunkInventoryManagement.Data.ApplicationUserRole", b =>
                {
                    b.HasOne("EtherpunkInventoryManagement.Data.ApplicationRole")
                        .WithMany("UserRoles")
                        .HasForeignKey("ApplicationRoleId");

                    b.HasOne("EtherpunkInventoryManagement.Data.ApplicationUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("ApplicationUserId");
                });
#pragma warning restore 612, 618
        }
    }
}
